# Generated by Django 4.0.5 on 2022-09-14 15:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(default='media/no_image.png', max_length=255, verbose_name='image'),
        ),
    ]
