# Generated by Django 4.0.5 on 2022-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(default='media/no_image.png', upload_to='store'),
        ),
    ]
